### ISSUE TITLE
Festival Guide- Sponsors page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1099] opened 2018-09-10 16:23 UTC
Sponsors  page 

(suggested word count: 190 )

@consuelamckenzie  can you work with @jcbarajas and #Jessie to get this content before Thursday?

**Comment by gideonthomas** [comment] 2018-09-13 18:59
Hi @consuelamckenzie, just checking in on this ticket...do we have content ready for this?

**Comment by consuelamckenzie** [comment] 2018-09-13 20:56
@gideonthomas 
We do indeed. 

Many logos are pending, we have sticker mule already and I will be dropping the rest of the incoming logos into this shared folder.

https://drive.google.com/open?id=1zWZdMp3xCjaisMM7ZDJP5_3syLUmTmEt

Maybe sponsors are;
APPLE; BOX; DIGITAL IMPACT ALLIANCE, FIGMA, SALESFORCE

**Confirmed **
Private Internet Access (pending logo)
Presenting Festival Partner

Internet Society
Science Fair Partner

Eyeo (pending logo)
Welcome Event Partner

Sticker Mule (you have logo)
Closing Party Partner

Samsung (pending logo)
Youth Zone Partner


**Text**

Thank you MozFest 2018 sponsors! 

Your support helps us reach thousands of people through the world’s leading event for a healthy internet. Together, we’re connecting and fueling the people, ideas, and tools that will keep the web open, safe, inclusive, and accessible for the billions who use it every day.

Please join us thanking our sponsors in person throughout the festival and on Twitter at #MozFest2018.

To learn more about MozFest sponsorship, please contact us at sponsor@mozillafoundation.org  

@jcbarajas for your reference.

**Comment by gideonthomas** [comment] 2018-09-14 18:48
Many thanks @consuelamckenzie! Would you also be able to provide links for the Sponsors as well (since they will also be going on the website). Also, do we have tiers for the sponsors that we're showing? Or are we just listing all of them and what kind of sponsorship they're providing?

@Saallen would you be able to review the copy above? One suggested change I have is to replace:
> Please join us thanking our sponsors in person throughout the festival and on Twitter at #MozFest2018. 

with
"Please join us in thanking our sponsors in person throughout the festival and on Twitter using #MozFest2018."

**Comment by consuelamckenzie** [comment] 2018-09-15 06:10
@gideonthomas as of Friday this is what the sponsorship looks like

Partnerships are unconfirmed with the following organizatons;
[Apple](https://www.apple.com/uk/); [Box](https://www.box.com/en-gb/home); [Digital Impact Alliance](https://digitalimpactalliance.org/), [Figma](https://www.figma.com/), [Salesforce
](https://www.salesforce.com/), [UX Fabric](http://www.uxfabric.com/) 

**Confirmed **

Private Internet Access (pending logo)
Presenting Festival Partner

[Internet Society](https://www.internetsociety.org)[ Logo](https://assets.internetsociety.org/Styleguide/#page/029105C2-BD06-4184-9C413CD5BAB15B76)
Science Fair Partner

Eyeo (pending logo) - **Cancelled please remove**
Welcome Event Partner

[Sticker Mule](https://mule.to/mozfest-2018) [(Logo](https://drive.google.com/open?id=13iK-2G5L6XjX2Tv4yJDAIHeGQBHQndfp))
Closing Party Partner

[Samsung](https://www.samsung.com/uk/apps/samsung-internet/) ([Logo](https://drive.google.com/open?id=1SDf1_ndD_cH42uBU39QZJ6iYvhyqHZ9s))
Youth Zone Partner

@jcbarajas for reference

**Comment by Saallen** [comment] 2018-09-16 20:30
Hey @consuelamckenzie 
Our hastag is just MozFest- this is where all our comms and content goes, 
 I amended it in the copy to say mozfest so let me know asap if you want to keep the year at the end

**Comment by consuelamckenzie** [comment] 2018-09-18 00:19
> Hey @consuelamckenzie
> All our comms and content go to hashtag MozFest. It's been amended in the copy to say mozfest, double checking you are happy to drop the '2018' from the hashtag?

Hi Juan @jcbarajas are you happy with this small amendment to the copy?

**Comment by jcbarajas** [comment] 2018-09-18 03:46
Hi Consuela,

It’s good with me. Thanks for checking.

Juan

**Comment by gideonthomas** [comment] 2018-09-18 19:17
Thanks @consuelamckenzie! I updated the list [here](https://github.com/mozilla/mozillafestival.org/issues/1027#issuecomment-418504263) as well. Please continue to update this thread until September 28, after which the final list of sponsors I get from this thread will go off to print.

**Comment by gideonthomas** [comment] 2018-09-24 20:38
Closing as done in the main festival guide ticket

**Closed by gideonthomas** 2018-09-24 20:38 UTC
Labels: Content :zap:, Festival Guide
